---
title: "Philosophy of science"
author: "Pia"
format: html
editor: visual
bibliography: references.bib
---

## Falsifikasjonisme

*Hva er Poppers falsifiserbarhetskriterium og hvilket spørsmål skal dette kriterium gi svar på? Hvorfor mener andre vitenskapsfilosofer (f.eks. Okasha) at vi ikke trenger å svare på dette spørsmålet? Hvem synes dere har rett?*

The falsification principle was first developed by Karl. R. Popper in an attempt to answer the question "what is science". In principle, theories cannot be confirmed, because it can never be ruled out that contradictory cases that conflict with them will arise sometime in the future. Nevertheless, theories can be falsified by empirical observations. One well known empirical observation is "all swans are white", which can be falsified by seeing a black swan. It was important to Popper to separate "real" science from pseudo-science, which led to him ask himself how to do just that. He didn't agree with the empirical method that was being used, which was the inductive method. When using the inductive method one does research and then derives a theory from that. He thought that researchers should argue deductively, which means to come to a specific conclusion -- from a more general idea.

An example Popper [-@popper1985] wrote about looked at human behaviour: one man tried to drown a child by pushing it into the water while another man jumped into the water to try save the child - even if that meant he could die. Both scenarios could be explained from Freud's and Adler's standpoint and both ended with the fact that each man wanted to prove himself - for different reasons. Popper thought that the fact that the theories of Freud and Adler always fitted was their biggest weakness. Admirers of those theories saw that fact as their biggest strength. It was important to Popper to clearly divide science from pseudo-science and draw a line between these two. He called his criterion the criterion of demarcation [@popper1985].

Popper disagreed with Marx's theories of history, psychoanalysis and individual psychology as well. He thought they were more similar to primitive myths than science. He thought people who liked Marx's work were fascinated by the apparent explanatory power of his theories [@popper1985]. Popper also thought of Freud's psychoanalytic theory as pseudo-science because it could be "rendered compatible with any clinical data \[...\] it was thus unfalsifiable" [@okasha2016]. Critics say that Popper's falsification principle is too simplistic. Some of the methods that Popper criticised were used by well-respected scientists and actually led to major discoveries. Okasha [-@okasha2016] argues separating science from pseudo-science is not as easy as Popper thinks. In his eyes, Popper failed at his attempt to separate the two, but he also wonders if it actually is possible to come up with a common feature that all things "science" share. However, Okasha [-@okasha2016] doesn't think that one simple feature that separates science from pseudo-science can be found. There might not be an answer to the question "what is science".

I am not quite sure who is right, as I really do not have a lot of knowledge in this area. But I do think that it would be useful to be able to clearly separate science from pseudo-science. It would be very helpful to be able to see right away what "real" science is and make it easier to work with. However, I think that Okasha and other critics make good points as well and it is hard to completely let go of a theory only because the findings don't go with it 100%. It might just be that those findings inspire a different approach which then could lead to important discoveries.

## HD-metoden og abduksjon

*Hva er strukturen på et bekreftende vitenskapelig argument ifølge den hypotetisk deduktive metode? Forklar ut fra Hempels artikkel, men bruk egne eksempel. Sammenlign også Hempels HD-metode med hvordan vitenskapelig bekreftelse fungerer ifølge abduksjon.*

The hypothetico-deductive-model (HD-model) is a proposed description of the scientific method. According to this, scientific investigation is done by formulating a hypothesis in a form that is falsifiable, using a test on observable data, the outcome of which is not yet known. A test result that could and does contradict the predictions of the hypothesis is considered a falsification of the hypothesis. A test result that could have contradicted the hypothesis but does not contradict it confirms the theory.

The first step when following the HD-model is building a hypothesis [@hempel1966]. The second step is the deduction of the observable consequences followed by the testing of the hypothesis in step three. In the last and fourth step, the conclusion from observation to hypothesis is made [@hempel1966]. An example for the HD-model could be the following: The car stopped working and a hypothesis could be that the reason for a non-working car is an empty fuel tank (step one). If the fuel tank is filled with gas, the car should be working again (step two). The fuel tank is being filled with gas to test the prediction (step three). If the car is now working again, the hypothesis is confirmed (step four). If the car on the other hand does not work, the prediction was false. This could lead to a rejection of the hypothesis, and one would need to think of another hypothesis and repeat some of the steps.

Another scientific method is abduction. Unknown causes are derived from known consequences or effects. A simple example for this method would be to say that if it rains, the grass is wet. This means, that when the grass is wet, it has rained. In abductive conclusions, explanatory hypotheses or perspectives are generated from which necessary implications are derived by deduction. Those then need to be tested experimentally. The probability of the hypotheses can be deduced inductively from the results of the test. However, a problem of the abductive conclusion is the fact that one cannot be certain that out of all the different possible explanations the right one has been chosen. Returning to the previous example, there could be many different reasons for the grass being wet. One could have e.g. turned on the water sprinkler which then led to wet grass.

To compare abduction with the HD-model we can return to the car example. If the car started working again after the fuel tank was filled one could come up with the hypothesis that a full fuel tank is what's responsible for a working car. That's when the HD-model is being used. When using abduction there would be more factors that could influence if a car is working or not and lead to a hypothesis. Apart from the full fuel tank, another reason for a working car could be that it's owner wanted it to work and thought about a working car really hard. Obviously this hypothesis doesn't make sense and would not be explored further, which leaves the first hypothesis. In abduction the most logical hypothesis is usually the one that gets chosen to explain a observation. However, more unlikely hypotheses can also have their place and help explore other possible perspectives.

## Replikasjonskrisen

*Hva mener Alexander Bird er forklaringen til at mange resultat i noen vitenskaper ikke repliseres? Oppsummere Birds argument for dette. Sammenlign også Birds forklaring med noen av de andre forklaringene som Bird diskuterer i seksjon 4. Har Bird rett i at hans forklaring er bedre?*

Replicability is a requirement within scientific research and means that a study can be repeated under the same conditions and by using the same method as in the original research and should then result in the same findings. The replication crisis in social psychology and clinical biomedicine describes therefore the problem that there is a risk that the results of studies cannot always be confirmed when repeated [@bird2021]. The first thing that comes to mind as a reason for that is low-quality research. Bird [-@bird2021] is nevertheless convinced, that this can happen, even when the scientists conducted good and thorough research.

An example of the replication crisis is the following: A biotech company attempted to reproduce 53 studies over the course of 10 years in the field of oncology. Of those 53 studies only 6 studies could be recreated satisfactorily. Those 6 studies make up for 11%, which leaves 89% of failed tries of replication [@bird2021]. According to Bird [-@bird2021], the reason for those failed attempts at replication can be the base rate fallacy. The base rate fallacy is the false positive paradox, in which false positives are more likely than true positives. A true positive is a finding where the model correctly predicts the positive outcome. A false positive on the other hand means that a test gives a positive result when it should actually be a negative. An example for that could be getting a positive result on a pregnancy test even though the person is not pregnant. A goal is therefore to reduce the false positives to avoid false conclusions. To explain the base rate fallacy further Bird [-@bird2021] uses this example: the profiling of airline passengers to see if they are terrorists by scanning their appearance and behaviour as an indicator for them being a terrorist. The test is correct in 95% of cases. This means that if this test would be done on 100 passengers who are not terrorists, 5 of them would get a false positive result, saying they are terrorists, even if they are not. It is therefore important that researchers don't neglect the base rate.

Apart from the base rate fallacy there are also some other explanations of the replication crisis, according to Bird [-@bird2021]. Those are low statistical power, publication bias, questionable research practices and fraud, to name a few. Bird [-@bird2021] does not think that the low statistical power of some studies explains the replication crisis. Even if the statistical power was increased, the positive predicted value (PPV) would not change that much. To improve the PPV, the number of false positives needs to be decreased. Things that increase statistical power are e.g. bigger sample size. Even though the statistical power should be increased, it can not be the only explanation for the crisis. Even if the power was as high as 100% it would still leave a 31% false positive report rate. Another possible explanation of the replication crisis could be publication bias [@bird2021]. This can occur when the results and findings of a study affect whether or not it will get published. At the present moment studies with negative outcomes get published less than the ones which show statistically significant results. This can either happen because the researchers don't want to publish their findings or because the journals won't publish the results. Though, according to Bird [-@bird2021], this cannot solely explain the replication crisis, because it does not give an explanation for the false positive results. If there is a strong bias where only positive results get published, the journals would still have a lot of requirements to ensure good quality research. This would result in high standards for the statistical significance, which in turn makes the positive results that get published very likely to be true. There would be few false positives and without those there can be no replication crisis [@bird2021]. However, those false positive results do exist.

To fix the problem Bird [-@bird2021] suggests coming up with hypotheses that "are more likely to be true". Additionally, the quality of research should be lifted even more. He suggests a lower α than 0.05, which is seen as adequate as of now. The lower the α, the more statistically significant the result. It might however be hard to lower the α, depending on the science.

In his conclusion Bird [-@bird2021] says: "It is important to be aware that even well-performed research can be quite likely to produce a false positive result. Recognizing this might reduce the acrimony and tension that surrounds failed replication.", which I think is a good thing to keep in mind.

## References
